name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 0 * * 5" # JST 9:00 (Fri)

jobs:
  test_main:
    strategy:
      fail-fast: false

      matrix:
        ruby:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"

          # FIXME: workaround for https://github.com/itamae-kitchen/itamae/issues/377
          # - "3.4"
          - "3.4.2"
        rubyopt:
          - ""
          - "--jit"
          - "--yjit"
        exclude:
          # --jit is available since MRI 2.6
          - ruby:    "2.3"
            rubyopt: "--jit"
          - ruby:    "2.4"
            rubyopt: "--jit"
          - ruby:    "2.5"
            rubyopt: "--jit"
          # --yjit is available since MRI 3.1
          - ruby:    "2.3"
            rubyopt: "--yjit"
          - ruby:    "2.4"
            rubyopt: "--yjit"
          - ruby:    "2.5"
            rubyopt: "--yjit"
          - ruby:    "2.6"
            rubyopt: "--yjit"
          - ruby:    "2.7"
            rubyopt: "--yjit"
          - ruby:    "3.0"
            rubyopt: "--yjit"

          # --jit is same to --yjit since MRI 3.2 (don't test both `--jit` and `--yjit`)
          - ruby:    "3.2"
            rubyopt: "--yjit"
          - ruby:    "3.3"
            rubyopt: "--yjit"
        include:
          # ruby-debug is the same as ruby-head but with assertions enabled (-DRUBY_DEBUG=1)
          - ruby: "debug"
            rubyopt: "" # See also https://bugs.ruby-lang.org/issues/20205 (enable frozen string literal as default)
          - ruby: "debug"
            rubyopt: "--disable=frozen-string-literal"

          # FIXME: workaround for https://github.com/itamae-kitchen/itamae/issues/377
          - ruby:    "3.4"
            rubyopt: "--yjit"
          - ruby:    "3.4.2"
            rubyopt: "--yjit"

    uses: ./.github/workflows/test_main.yml
    with:
      ruby: ${{ matrix.ruby }}
      rubyopt: ${{ matrix.rubyopt }}

      # This repository uses matrix to run 50+ builds in a pipeline.
      # This results in simultaneous requests being sent to httpbin.org,
      # similar to a DDoS attack, often causing 500 errors and test failures.
      #
      # e.g. https://github.com/itamae-kitchen/itamae/actions/runs/17045210601/job/48319099479?pr=379
      #
      # Therefore, I suppressed simultaneous requests to httpbin.org.
      skip_http_request_test: ${{ (matrix.ruby == '2.3' && matrix.rubyopt == '') && 'false' || 'true' }}
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  notify:
    needs:
      - test_main

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: lazy-actions/slatify@master
        if: always()
        continue-on-error: true
        with:
          job_name: '*notify*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
